#!/bin/bash

if [[ $# -eq 0 ]]; then
    source menu.sh

    case "$choice" in
        1)
            bash modules/system.sh
            ;;
        2)
            bash modules/disk.sh "$disk_path"
            ;;
        *)
            echo "Invalid choice. Exiting."
            exit 1
            ;;
    esac

else

    case "$1" in
        --help)
            bash help.sh
            ;;

        system)
            bash modules/system.sh
            ;;
        disk)
            bash modules/disk.sh "${2:-/}"
            ;;
        *)
            echo "Invalid option. Use --help to show system information."
            exit 1
    esac

fi